#define MIN_PASSWORD_LENGTH         (6)
#define MIN_PASSWORD_LENGTH_STR     "6"
#define MAX_PASSWORD_LENGTH         (128)
#define MAX_PASSWORD_LENGTH_STR     "128"

#define BCRYPT_PASS_HASH_ROUNDS     (10)