#define     COLOR_WHITE         (-1)
#define     COLOR_GREY          (0xBFBFBFFF)
#define     COLOR_GREEN         (0x37AB09FF)
#define     COLOR_YELLOW        (0xE6DE09FF)
#define     COLOR_PURPLE        (0xC2A2DAFF)
#define     COLOR_HARD_PURPLE   (0x5B3278FF)
#define 	COLOR_LIGHTRED 	    (0xFF6347AA)

#define     CWHITE          ("FFFFFF")
#define     CGREY           ("BFBFBF")
#define     CGREEN          ("37AB09")
#define     CYELLOW         ("E6DE09")
#define     CPURPLE         ("C2A2DA")
#define     CHARDPURPLE     ("5B3278")
#define 	CLIGHTRED 	    ("FF6347")