#define DICE_TABLE_DYNAMIC_ZONE_WIDTH (3.84)
#define DICE_TABLE_DYNAMIC_ZONE_LENGTH (2.89)
#define DICE_TABLE_OBJECT_ID (1824)

#define MAX_DICE_TABLES (20)
#define MAX_DICE_TABLE_PLAYES (5)

#define DICE_TABLE_AREA_MIN_ID (10000)
#define TABLE_AREA_MAX_ID (DICE_TABLE_AREA_MIN_ID + MAX_DICE_TABLES)

#define MIN_DICE_BET (1000)
#define MAX_DICE_BET (400000000)

#define MIN_DICE_BET_STR "1000"
#define MAX_DICE_BET_STR "400000000"

#define BONE_MIN_VALUE  (1)
#define BONE_MAX_VALUE  (6)

#define DICE_TIMER_TIME (15)
#define DICE_TIMER_TIME_STR "15"

#define DICE_MIN_PLAYERS_NEED_TO_START (2)

#define DICE_TABLE_SETBET_TD_IDX (1)
#define DICE_TABLE_DICE_TD_IDX (2)
#define DICE_TABLE_EXIT_TD_IDX (3)

#define DICE_TABLE_PLAYER_NAME_TD_IDX (0)
#define DICE_TABLE_PLAYER_RESULT_TD_IDX (1)
#define DICE_TABLE_BANK_TD_IDX (10)
#define DICE_TABLE_BET_TD_IDX (11)